### ISSUE TITLE
Доработка конструктора абонементов

### ISSUE THREAD

**Issue by VolodinD** [8clever/school-dance#18]
В конструкторе должно быть текстовое поле для управления текстом в правом блоке (сейчас есть возможность только менять само наименование абонемента)

**Comment by 8clever** [comment]
В данный момент реализована сущность ЦЕНА.
в разделе абонемента снизу кнопка + ЦЕНА
в правом блоке выпадает список цен.
Это нужно для того, если будет реализация оплаты на нашей стороне, то чтобы были конкретные цены с конкретной ссылкой на абонемент.
В это контексте текст не нужен,
